### ISSUE TITLE
WEBKIT_ROOT=..../qt5/qtwebkit, right?

### ISSUE THREAD

**Issue by msjang** [cablelabs/QtRUIBrowser#8]
Build Env: Ubuntu 12.04 LTS 64bit

I built qt5 in the following document.
https://community.cablelabs.com/wiki/display/CBLCVP2/Building+Qt+with+OpenSSL+TLS+authorization+extension+support

Is it right to set environment and run build script like this?

```
# Your path should be setup already from building WebKit, like so:
export QTDIR=/data/work/cvp2/qt5/qtbase
export PATH=$QTDIR/bin:$PATH

# This should point to your WebKit checkout
export WEBKIT_ROOT=/data/work/cvp2/qt5/qtwebkit

# This makes a debug version
qmake QtRUIBrowser.pro

# This makes a release version
# qmake QtRUIBrowser.pro CONFIG+=release CONFIG-=debug
```

**Comment by brendanlong** [comment]
The updated instructions are here:

https://github.com/cablelabs/webkit/wiki/Building-QtWebKit

We don't recommend using QtWebKit anymore though, since it has been abandoned by the Qt project. We have a GTK-based browser available if you want to use it:

https://github.com/cablelabs/webkit/wiki/Building-WebKitGTK
https://github.com/cablelabs/rui-browser-gtk
